### ISSUE TITLE
关于脚本转换的一点问题和建议

### ISSUE THREAD

**Issue by okou19900722** [cocos-creator/plugin-import-2.x#3]
# 问题

## 1、未知问题

我有几个脚本出现了 `import {eded} from "cc"`），疑似我的脚本中有succeeded（因为另一个脚本中我有个变量叫succeededEvent，然后变成了 `import {ededEvent} from "cc"`）,同时，方法名变了

目前主要碰到有以下几种情况：
|名称|类型|3.x|导入中多了的部分 |
|----|---|-----|-----|
|xxxSucceeded|方法|xxxSueded|import {eded} from "cc"|
|succeededEvent|属性|无变化|import {ededEvent} from "cc"|
|xxxSuccessed|方法|xxxSussed|import {ssed} from "cc"|

## 2、EventHandler的问题

2.x中，这个类全称是 `cc.Component.EventHandler`，3.x中，应该是 `import {EventHandler} from "cc";`。但当前转换之后是

```typescript
@property(Component.EventHandler)
xxx: Component.EventHandler = new Component.EventHandler();
```

## 3、spine的问题

2.x中，通常是sp.xxxxx来使用，3.x好像没有处理这个

# 建议

## 1、关于全局变量cc

我个人是比较喜欢用cc.xxx的，3.x中把全局的cc添加了deprecated，但是ts的语法是支持下面这种的
```typescript
import * as cc from "cc";
```
建议导入时，不要直接把cc.XXX给转换了，而是在最新面加上面这行代码。

或者作为可选项，由开发者决定。

## 2、关于property

当前转换的property的类型全部变成了 

```typescript
@property(Sprite)
xxxSprite: Sprite | null = null;
```

建议直接转换成
```typescript
@property(Sprite)
xxxSprite: Sprite = null!;
```

毕竟之前能跑的代码，大概率空安全问题不太会存在，这样的话，在修改逻辑的地方也比较好的处理。

暂时碰到了这么多

**Comment by knoxHuang** [comment]
感谢反馈，很好的建议，后续会再想想如何完善脚本转换

**Comment by okou19900722** [comment]
:joy: 都快1年了
